"""adiciona configuracao resumo diario

Revision ID: 3058f716df40
Revises: c420a200f2f2
Create Date: 2026-10-08 23:33:53.428980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3058f716df40'
down_revision = 'c420a200f2f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resumo_diario_configuracoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('meteorologia', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('tarefas', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('eventos', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('combustiveis', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('fim_de_semana', sa.Boolean(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['utilizadores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_resumo_diario_user')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resumo_diario_configuracoes')
    # ### end Alembic commands ###
