"""baseline

Revision ID: 3b14f5bd26a5
Revises: 
Create Date: 2026-10-06 11:48:04.398345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b14f5bd26a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('combustiveis_estado_atualizacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ultima_atualizacao', sa.DateTime(), nullable=True),
    sa.Column('ultima_execucao_sucesso', sa.Boolean(), nullable=True),
    sa.Column('mensagem_erro', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('combustiveis_postos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('tipo_posto', sa.String(length=50), nullable=True),
    sa.Column('morada', sa.String(length=300), nullable=True),
    sa.Column('localidade', sa.String(length=150), nullable=True),
    sa.Column('cod_postal', sa.String(length=20), nullable=True),
    sa.Column('concelho', sa.String(length=100), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('ciclos_ausente', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('combustiveis_postos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_combustiveis_postos_concelho'), ['concelho'], unique=False)

    op.create_table('utilizadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('ultimo_login', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('dois_fa_activo', sa.Boolean(), nullable=True),
    sa.Column('dois_fa_chat_id', sa.String(length=64), nullable=True),
    sa.Column('dois_fa_email_activo', sa.Boolean(), nullable=True),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('totp_activo', sa.Boolean(), nullable=True),
    sa.Column('dois_fa_codigo', sa.String(length=6), nullable=True),
    sa.Column('dois_fa_expira', sa.DateTime(), nullable=True),
    sa.Column('reset_token', sa.String(length=100), nullable=True),
    sa.Column('reset_token_expira', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('utilizadores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_utilizadores_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_utilizadores_username'), ['username'], unique=True)

    op.create_table('cofre_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('master_pw_hash', sa.String(length=256), nullable=False),
    sa.Column('salt', sa.String(length=64), nullable=False),
    sa.Column('kdf_iterations', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['utilizadores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('cofre_passwords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=128), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('dominio', sa.String(length=256), nullable=True),
    sa.Column('username', sa.String(length=256), nullable=True),
    sa.Column('password_cifrada', sa.LargeBinary(), nullable=False),
    sa.Column('iv', sa.LargeBinary(), nullable=False),
    sa.Column('tag', sa.LargeBinary(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('favorito', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['utilizadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cofre_passwords', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cofre_passwords_dominio'), ['dominio'], unique=False)
        batch_op.create_index(batch_op.f('ix_cofre_passwords_user_id'), ['user_id'], unique=False)

    op.create_table('combustiveis_precos_historico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('posto_id', sa.Integer(), nullable=False),
    sa.Column('tipo_combustivel', sa.String(length=100), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('data_atualizacao_dgeg', sa.String(length=50), nullable=True),
    sa.Column('data_recolha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['posto_id'], ['combustiveis_postos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('combustiveis_precos_historico', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_combustiveis_precos_historico_data_recolha'), ['data_recolha'], unique=False)
        batch_op.create_index(batch_op.f('ix_combustiveis_precos_historico_posto_id'), ['posto_id'], unique=False)

    op.create_table('combustiveis_utilizador_combustivel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tipo_combustivel', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['utilizadores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tipo_combustivel', name='uq_user_combustivel')
    )
    op.create_table('combustiveis_utilizador_concelho',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('concelho', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['utilizadores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'concelho', name='uq_user_concelho')
    )
    op.create_table('conversoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('num_ficheiros', sa.Integer(), nullable=False),
    sa.Column('tamanho_total_kb', sa.Integer(), nullable=False),
    sa.Column('convertido_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['utilizadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('convites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('criado_por', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('expira_em', sa.DateTime(), nullable=False),
    sa.Column('usado', sa.Boolean(), nullable=True),
    sa.Column('usado_em', sa.DateTime(), nullable=True),
    sa.Column('mailjet_message_id', sa.String(length=20), nullable=True),
    sa.Column('email_estado', sa.String(length=20), nullable=True),
    sa.Column('email_verificado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por'], ['utilizadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('convites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_convites_token'), ['token'], unique=True)

    op.create_table('etiquetas_nota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['utilizadores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome', 'user_id', name='uq_etiqueta_nota_user')
    )
    op.create_table('evento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('localizacao', sa.String(length=300), nullable=True),
    sa.Column('data_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_fim', sa.DateTime(), nullable=False),
    sa.Column('dia_inteiro', sa.Boolean(), nullable=True),
    sa.Column('cor', sa.String(length=20), nullable=True),
    sa.Column('notificar', sa.Boolean(), nullable=True),
    sa.Column('notificado_em', sa.Date(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['utilizadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jogos_euromilhoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('data_registo', sa.Date(), nullable=False),
    sa.Column('data_sorteio', sa.Date(), nullable=False),
    sa.Column('numeros', sa.String(length=20), nullable=False),
    sa.Column('estrelas', sa.String(length=6), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['utilizadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=64), nullable=False),
    sa.Column('icone', sa.String(length=8), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['utilizadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=256), nullable=True),
    sa.Column('corpo', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(length=16), nullable=True),
    sa.Column('cor', sa.String(length=16), nullable=True),
    sa.Column('fixada', sa.Boolean(), nullable=True),
    sa.Column('arquivada', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_edicao', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['utilizadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificacao_preferencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('telegram_activo', sa.Boolean(), nullable=True),
    sa.Column('telegram_chat_id', sa.String(length=64), nullable=True),
    sa.Column('email_activo', sa.Boolean(), nullable=True),
    sa.Column('notificar_resultados', sa.Boolean(), nullable=True),
    sa.Column('data_actualizacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['utilizadores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('tags_tarefa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['utilizadores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome', 'user_id', name='uq_tag_user')
    )
    op.create_table('user_modulos',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('modulo_slug', sa.String(length=32), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['utilizadores.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'modulo_slug')
    )
    op.create_table('itens_checklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=512), nullable=False),
    sa.Column('feito', sa.Boolean(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('nota_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['nota_id'], ['notas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nota_etiquetas',
    sa.Column('nota_id', sa.Integer(), nullable=False),
    sa.Column('etiqueta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['etiqueta_id'], ['etiquetas_nota.id'], ),
    sa.ForeignKeyConstraint(['nota_id'], ['notas.id'], ),
    sa.PrimaryKeyConstraint('nota_id', 'etiqueta_id')
    )
    op.create_table('tarefas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=512), nullable=False),
    sa.Column('concluida', sa.Boolean(), nullable=True),
    sa.Column('prioridade', sa.String(length=8), nullable=True),
    sa.Column('data_limite', sa.Date(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_conclusao', sa.DateTime(), nullable=True),
    sa.Column('notificada_em', sa.Date(), nullable=True),
    sa.Column('lista_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lista_id'], ['listas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['utilizadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tarefa_tags',
    sa.Column('tarefa_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags_tarefa.id'], ),
    sa.ForeignKeyConstraint(['tarefa_id'], ['tarefas.id'], ),
    sa.PrimaryKeyConstraint('tarefa_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tarefa_tags')
    op.drop_table('tarefas')
    op.drop_table('nota_etiquetas')
    op.drop_table('itens_checklist')
    op.drop_table('user_modulos')
    op.drop_table('tags_tarefa')
    op.drop_table('notificacao_preferencias')
    op.drop_table('notas')
    op.drop_table('listas')
    op.drop_table('jogos_euromilhoes')
    op.drop_table('evento')
    op.drop_table('etiquetas_nota')
    with op.batch_alter_table('convites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_convites_token'))

    op.drop_table('convites')
    op.drop_table('conversoes')
    op.drop_table('combustiveis_utilizador_concelho')
    op.drop_table('combustiveis_utilizador_combustivel')
    with op.batch_alter_table('combustiveis_precos_historico', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_combustiveis_precos_historico_posto_id'))
        batch_op.drop_index(batch_op.f('ix_combustiveis_precos_historico_data_recolha'))

    op.drop_table('combustiveis_precos_historico')
    with op.batch_alter_table('cofre_passwords', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cofre_passwords_user_id'))
        batch_op.drop_index(batch_op.f('ix_cofre_passwords_dominio'))

    op.drop_table('cofre_passwords')
    op.drop_table('cofre_configs')
    with op.batch_alter_table('utilizadores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_utilizadores_username'))
        batch_op.drop_index(batch_op.f('ix_utilizadores_email'))

    op.drop_table('utilizadores')
    with op.batch_alter_table('combustiveis_postos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_combustiveis_postos_concelho'))

    op.drop_table('combustiveis_postos')
    op.drop_table('combustiveis_estado_atualizacao')
    # ### end Alembic commands ###
