"""add_column mailjet fields to convites

Revision ID: 5c1fceddeb88
Revises: 9a0a3ad080d6
Create Date: 2026-10-05 20:32:31.091095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c1fceddeb88'
down_revision = '9a0a3ad080d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('convites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mailjet_message_id', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('email_estado', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('email_verificado_em', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('convites', schema=None) as batch_op:
        batch_op.drop_column('email_verificado_em')
        batch_op.drop_column('email_estado')
        batch_op.drop_column('mailjet_message_id')

    # ### end Alembic commands ###
